name: Angular CI/CD to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Push
    runs-on: Ubantu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p  "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/divya-portfolio:latest

  deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    needs: build
    steps:
      - name: Docker pull image
        uses: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/divya-portfolio:latest

      - name: docker stop container
        run: sudo docker stop divya-portfolio || true
      - name: docker rm container
        run: sudo docker rm divya-portfolio || true

      - name: docker run container
        run: sudo docker run -d -p 4200:4200 --name divya-portfolio ${{ secrets.DOCKER_USERNAME }}/divya-portfolio:latest
